import type { Metadata } from 'next'
import { Roboto, Courier_Prime } from 'next/font/google'
import './globals.css'
import { Navbar } from './components/Navbar'


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700']})
const courier = Courier_Prime({ subsets: ['latin'], weight: '400', variable:'--font-courier' })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} ${courier.variable}`}>
         <Navbar/>
         {children}</body>
    </html>
  )
}
